import { supabase } from "./supabase-config.js";

// ── camelCase ↔ snake_case mapping ──

function toSnakeCase(data) {
  const map = {
    postalCode: "postal_code",
    jobTitle: "job_title",
    motivationParagraph: "motivation_paragraph",
    skillsParagraph: "skills_paragraph",
    createdAt: "created_at",
  };
  const result = {};
  for (const [key, value] of Object.entries(data)) {
    const snakeKey = map[key] || key;
    result[snakeKey] = value;
  }
  return result;
}

function toCamelCase(row) {
  const map = {
    postal_code: "postalCode",
    job_title: "jobTitle",
    motivation_paragraph: "motivationParagraph",
    skills_paragraph: "skillsParagraph",
    created_at: "createdAt",
    user_id: "userId",
  };
  const result = {};
  for (const [key, value] of Object.entries(row)) {
    const camelKey = map[key] || key;
    result[camelKey] = value;
  }
  return result;
}

// ── CRUD Operations ──

export async function createApplication(data) {
  const row = toSnakeCase(data);
  // Remove id if present (auto-generated by DB)
  delete row.id;
  row.status = row.status || "brouillon";

  const { data: inserted, error } = await supabase
    .from("applications")
    .insert(row)
    .select()
    .single();
  if (error) throw error;
  return inserted.id;
}

export async function getAllApplications() {
  const { data, error } = await supabase
    .from("applications")
    .select()
    .order("created_at", { ascending: false });
  if (error) throw error;
  return data.map(toCamelCase);
}

export async function getApplicationById(id) {
  const { data, error } = await supabase
    .from("applications")
    .select()
    .eq("id", id)
    .single();
  if (error) throw error;
  return toCamelCase(data);
}

export async function updateApplication(id, data) {
  const row = toSnakeCase(data);
  delete row.id;
  delete row.user_id;
  delete row.created_at;

  const { error } = await supabase
    .from("applications")
    .update(row)
    .eq("id", id);
  if (error) throw error;
}

export async function deleteApplication(id) {
  // Delete associated documents first
  const { data: user } = await supabase.auth.getUser();
  if (user?.user) {
    const folder = `${user.user.id}/${id}`;
    const { data: files } = await supabase.storage
      .from("documents")
      .list(folder);
    if (files && files.length > 0) {
      const paths = files.map((f) => `${folder}/${f.name}`);
      await supabase.storage.from("documents").remove(paths);
    }
  }

  const { error } = await supabase.from("applications").delete().eq("id", id);
  if (error) throw error;
}

// ── Storage (PDF documents) ──

export async function uploadDocument(blob, applicationId, filename) {
  const { data: user } = await supabase.auth.getUser();
  if (!user?.user) throw new Error("Not authenticated");

  const path = `${user.user.id}/${applicationId}/${filename}`;
  const { error } = await supabase.storage
    .from("documents")
    .upload(path, blob, { upsert: true, contentType: "application/pdf" });
  if (error) throw error;
  return path;
}

export async function getDocumentUrl(path) {
  const { data, error } = await supabase.storage
    .from("documents")
    .createSignedUrl(path, 3600);
  if (error) throw error;
  return data.signedUrl;
}

export async function listDocuments(applicationId) {
  const { data: user } = await supabase.auth.getUser();
  if (!user?.user) return [];

  const folder = `${user.user.id}/${applicationId}`;
  const { data, error } = await supabase.storage.from("documents").list(folder);
  if (error) throw error;
  return (data || []).map((f) => ({
    name: f.name,
    path: `${folder}/${f.name}`,
  }));
}

// ── Statuses ──

export const STATUSES = [
  { value: "brouillon", label: "Brouillon", color: "#8a95a8" },
  { value: "envoyée", label: "Envoyée", color: "#3b82f6" },
  { value: "relancée", label: "Relancée", color: "#f59e0b" },
  { value: "entretien", label: "Entretien", color: "#8b5cf6" },
  { value: "refusée", label: "Refusée", color: "#ef4444" },
  { value: "acceptée", label: "Acceptée", color: "#22c55e" },
];
